name: Release

on:
  push:
      branches:
        - "master"
      
jobs:
  docker_job:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.33.0'
      - uses: extractions/setup-just@v1
      - name: Calculate release version
        id: theVersion
        run: echo "::set-output name=theVersion::$(echo ${GITHUB_REF##*/})"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u subham328 -p Ak@sh328
      - name: Build docker image
        run: |
          just VERSION=${{ steps.theVersion.outputs.theVersion }} _build-latest
#       - name: Upload Helm artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: "helm"
#           path: "opa-${{ steps.theVersion.outputs.theVersion }}.tgz"

#   helm_job:
#     name: Helm chart
#     runs-on: ubuntu-latest
#     needs: docker_job
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: gh-pages
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v2
#         id: download
#         with:
#           name: helm
#           path: /tmp/helm
#       - name: Update Helm index
#         run: |
#           helm repo index /tmp/helm --merge ./charts/index.yaml
#           mv -f /tmp/helm/* ./charts
#       - name: Publish index and chart to gh-pages
#         uses: actions-js/push@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: gh-pages
